### ISSUE TITLE
Fix size on Attachements page

### ISSUE THREAD

**Issue by Yurenko** [ita-social-projects/SpaceToStudy-Client#1088]
In my resources on the attachment tab.

It should show the correct size.

![image](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/83120263/ad4d3c61-c697-4332-9a8a-446ab877756f)

**Comment by TSlashDreamy** [comment]
We have new mockup, do we really need to keep attachment size?
![зображення](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/45912519/420db92e-15ea-4445-8cc6-f2e20180c292)

**Comment by TSlashDreamy** [comment]
Not relevant, as we have a new design
![зображення](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/45912519/cc510477-e870-4524-ae60-632c85be192b)
