### ISSUE TITLE
(SP: 1) Add question should redirect on page in question page

### ISSUE THREAD

**Issue by Mav-Ivan** [ita-social-projects/SpaceToStudy-Client#1148]

**Comment by TSlashDreamy** [comment]
In question table
![зображення](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/45912519/f372f4b6-38ed-4c3f-8c09-e70f01c00bd2)

"new question" button already have redirect to new question page
![зображення](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/45912519/f5cf558c-1e05-430d-9f50-d41c766e686b)
