### ISSUE TITLE
(SP: 2)[Chat] Add posibility to delete chat 

### ISSUE THREAD

**Issue by Mav-Ivan** [ita-social-projects/SpaceToStudy-Client#1188]
Add posibility to delete chat only for you
https://www.figma.com/file/liJZDYhUnDP15Pi9bipDcv/Space2Study-(Students)?type=design&node-id=8892-72659&mode=design&t=zEHZErMaBFOAPjXl-4

**Comment by TSlashDreamy** [comment]
### **BLOCKED for now**

**Reason:** 
We don't have functionality in backend to delete chat
![зображення](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/45912519/ac2ad063-2894-42e4-b9f1-0156a408c9c5)

**Comment by TSlashDreamy** [comment]
### BLOCKED 14.10.23

**Reason:**
To implement chat deletion (from current user side), we need to implement next two endpoints in backend:

- `patch` method - to add `deletedFor` field, where we can put user id's that deleted chat for themselfs
- `delete` method - to completely delete the chat if both users have deleted the chat for themselfs

![зображення](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/45912519/9e226037-9ff6-4795-80e2-1246ba87b8ba)
