### ISSUE TITLE
(SP: 2)[Chat] Add posibility to clear history

### ISSUE THREAD

**Issue by Mav-Ivan** [ita-social-projects/SpaceToStudy-Client#1189]
Add posibility to clear history only for you
https://www.figma.com/file/liJZDYhUnDP15Pi9bipDcv/Space2Study-(Students)?type=design&node-id=8892-72662&mode=design&t=zEHZErMaBFOAPjXl-4

**Comment by TSlashDreamy** [comment]
### BLOCKED 07.11.23

**Reason:**
To implement history cleaning in chat (from the current user side), we need to implement the next endpoint in the backend:

- `patch` endpoint (`/chats/{id}/messages`) - to add `clearedFor` field, where we can put user id's that cleared chat history for themselves, and if we already have the user in this field, then just deleting this message

![зображення](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/45912519/21afcd81-6708-4411-b9eb-15465d17264d)
