### ISSUE TITLE
[My resources page] Translation bug on category deletion modal

### ISSUE THREAD

**Issue by TSlashDreamy** [ita-social-projects/SpaceToStudy-Client#1256]
**Description:** Deletion title is not displayed correctly

**Environment:** Windows 11 x64, Firefox Developer Edition 119.0b6.

**Reproducible:** always.

**Preconditions:**
The https://s2s-front-stage.azurewebsites.net/ site is opened.
The user is logged in as a Tutor.

**Steps to reproduce:**
1. Click "My Resources" in the navigation bar.
2. Select "Categories" tab.
3. Delete category.

**Actual result:**
We have wrong translation
![зображення](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/45912519/91f60762-3a76-415e-8ca0-b654ecdc7a7a)

**Expected result:**
P.s: No need to change description
![зображення](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/45912519/08d624ac-f898-469c-a18e-b8f23ec0c9ce)

**Comment by thomasmarconi** [comment]
Could you assign me to this?
