### ISSUE TITLE
[My resources page] Translation bug on category deletion notification

### ISSUE THREAD

**Issue by TSlashDreamy** [ita-social-projects/SpaceToStudy-Client#1359]
**Description:** Deletion notification text is not displayed correctly

**Environment:** Windows 11 x64, Firefox Developer Edition 119.0b6.

**Reproducible:** always.

**Preconditions:**
The https://s2s-front-stage.azurewebsites.net/ site is opened.
The user is logged in as a Tutor.

**Steps to reproduce:**
1. Click "My Resources" in the navigation bar.
2. Select "Categories" tab.
3. Delete category.

**Actual result:**
We have wrong translation
![зображення](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/45912519/41542944-b7eb-462a-a7cc-18b72e530106)

**Comment by SirJoraH21** [comment]
Hey, I'd like to take this issue

**Comment by SirJoraH21** [comment]
Seems to me like everything works fine.
Tested locally and on the [staging](https://s2s-front-stage.azurewebsites.net/my-resources) 
<img width="586" alt="image" src="https://github.com/ita-social-projects/SpaceToStudy-Client/assets/38436110/c8677eac-e2f8-43b6-bcfd-0489eb39c845">

**Comment by OlyaKorchan** [comment]
> 3\. Delete category.

Thank you for your comment. I have checked this and everything is working correctly right now. I will close the issue.

**Comment by OlyaKorchan** [comment]
This issue is a duplication of issue #1352 
It was fixed already and merged in #1353 to develop
