### ISSUE TITLE
(SP: 1) Create open list resources for cooperation

### ISSUE THREAD

**Issue by dmtrth25** [ita-social-projects/SpaceToStudy-Client#1549]
When add resources it should be Open (mocked)

<img width="364" alt="image" src="https://github.com/ita-social-projects/SpaceToStudy-Client/assets/56305508/0b5c029a-c86a-4b1b-9ce9-516dccfec65a">

https://www.figma.com/file/liJZDYhUnDP15Pi9bipDcv/Space2Study-(Students)?node-id=13638%3A50319&mode=dev

**Comment by OlyaKorchan** [comment]
Part of the issue #1555
