### ISSUE TITLE
[Tutor’s Find offers page] The placeholder text is not corresponded to the mockup in the search input

### ISSUE THREAD

**Issue by AntonOkun** [ita-social-projects/SpaceToStudy-Client#1637]
**Description:** The placeholder text is not corresponded to the mockup on the tutor’s Find offers page search input.

**Environment:** Windows 10 x64, Microsoft Edge 121.0.2277.128, Google Chrome 121.0.6167.189.

**Reproducible:** always.

**Build found:**

**Preconditions:**
The https://s2s-front-stage.azurewebsites.net/ site is opened.
The user is logged in as a Tutor.

**Steps to reproduce:**
1. Click on the “Find Offer” button on the home page header.
2. Click on the “All offers” button on the “Find Offer” dropdown.
3. Take a look at the placeholder text in the “Find offers” page search input.

**Actual result:**
The placeholder text is not corresponded to the mockup on the tutor’s Find offers page search input.
![image](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/129941062/a8b3d95a-5edd-4720-a4db-9b4cfbadad32)

**Expected result:**
The placeholder text is matched to the mockup on the tutor’s Find offers page input search.
![image](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/129941062/d6973fb1-8b29-4d6f-8ae8-e0ee164375d8)

**User story and test case links**
User Story Find student page view #1634
Test Case Check the tutor’s Find offers page UI #1635

**Comment by abalanovsky** [comment]
Already fixed
