### ISSUE TITLE
(SP:1) (Tutor Edit Profile) Create notification tab

### ISSUE THREAD

**Issue by Tolik170** [ita-social-projects/SpaceToStudy-Client#1658]
![image](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/63456632/90beece7-6c56-41e1-8724-a2662f253398)

**Comment by abalanovsky** [comment]
## Prior agreement to change items.

- Change of offer status
- Chat message
- Subscription to offers
- Email notifications
