### ISSUE TITLE
(SP:) Implement finished cooperations counter

### ISSUE THREAD

**Issue by abalanovsky** [ita-social-projects/SpaceToStudy-Client#1680]
Implement **finished** cooperations counter and display them at tutor's profile

<img width="921" alt="Знімок екрана 2024-03-25 о 17 13 33" src="https://github.com/ita-social-projects/SpaceToStudy-Client/assets/108689551/ca4430a0-74ab-4f48-b0d0-0a8bd0bf8922">

**Comment by ipasic-softserve** [comment]
Not relevant
