### ISSUE TITLE
Epic: SCSS design system

### ISSUE THREAD

**Issue by dmtrth25** [ita-social-projects/SpaceToStudy-Client#1745]
As example about design system
https://softserveacademy.udemy.com/course/react-for-senior-engineers
#### Design systems examples:
- [Fluent UI (Microsoft)](https://developer.microsoft.com/en-us/fluentui#/)
- [Carbon (IBM](https://carbondesignsystem.com/elements/2x-grid/overview/)
- [Polaris (Shopify)](https://polaris.shopify.com/)

[SCSS documentation](https://sass-lang.com/documentation/)

#### Linked tasks:
- [x] #1746
- [x] #1750 
- [x] #1751 
- [x] #1770 
- [x] #1775 
- [x] #1771
- [x] #1772
- [x] #1807
- [ ] Investigate MUI components which are widely used in projects without wrapper and create a custom wrapper for it (Box f.e)
- [ ] All custom components should be depended from custom props and then all mui styles should be applied inside custom component

**Comment by YaroslavChuiko** [comment]
This epic was successfully accomplished
