### ISSUE TITLE
(SP: 2) implement a profile filling scale 

### ISSUE THREAD

**Issue by Mygal-Alex** [ita-social-projects/SpaceToStudy-Client#1762]
![image](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/101183408/530144ba-06f8-4c68-be92-4a2962c89802)
### [Link to figma for student view](https://www.figma.com/file/liJZDYhUnDP15Pi9bipDcv/Space2Study-(Students)?type=design&node-id=1063-47644&mode=design&t=6nRpgNqTGZtT1i8l-0)
![image](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/105641724/3059f37e-b36e-42df-9bd6-3a7780aaeb27)

### [Link to figma for tutor view](https://www.figma.com/file/liJZDYhUnDP15Pi9bipDcv/Space2Study-(Students)?type=design&node-id=17789-48641&mode=design&t=6nRpgNqTGZtT1i8l-0)
![image](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/105641724/b6a99b25-e280-4d55-ab2a-4d04aee2a135)

For tutor: Add step - 'Add a video'

When filling scale is finished, it should be removed from profile

**Comment by asya982** [comment]
Blocked by #1830 
+ needed the backend response to be updated

**Comment by ipasic-softserve** [comment]
Duplicate #408
