### ISSUE TITLE
(SP: 1) Fix save cooperation logic

### ISSUE THREAD

**Issue by asya982** [ita-social-projects/SpaceToStudy-Client#1906]
### Expected result:
After saving cooperation the preview of it should render, details and create new tabs should show relevent components

### Actual result:
After saving cooperation activities edit component is persisent in all tabs (edit, activities, details)

https://github.com/ita-social-projects/SpaceToStudy-Client/assets/127191734/e36eb50e-3a39-4898-8517-b8ad3767edbe

**Comment by PavloDolia** [comment]
not relevant, the task has already done
