### ISSUE TITLE
(SP: ) Add useBlocker to 'Back to your personal profile button' 

### ISSUE THREAD

**Issue by OliaHrytsak** [ita-social-projects/SpaceToStudy-Client#1952]
Move useBlocker into separate reusable component and integrate into profile Tab and ProfessionalInfo Tab

![image](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/127191734/50a7c7a6-5743-4775-857a-4ee9a36d0662)

**Comment by docia** [comment]
not relevant
