### ISSUE TITLE
(SP: ) Fix sonnar errors

### ISSUE THREAD

**Issue by D1nviz** [ita-social-projects/SpaceToStudy-Client#1956]
Investigate and fix sonnar issues. (you can see them in develop branch commits list)

![image](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/118522791/9b634caa-79af-4676-987e-fd98e51e06a3)

![image](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/118522791/f91d4eaa-bd42-4949-aedf-eabc497c5f3d)

**Comment by docia** [comment]
not relevant
