### ISSUE TITLE
(SP: 0.5) Check auth-service.ts warning

### ISSUE THREAD

**Issue by abalanovsky** [ita-social-projects/SpaceToStudy-Client#1972]
Check auth-service.ts warning

<img width="1038" alt="Знімок екрана 2024-06-19 о 14 15 04" src="https://github.com/ita-social-projects/SpaceToStudy-Client/assets/108689551/c9b922a3-2f6e-4671-a7e7-81326c2ddccf">

**Comment by YulichkaR** [comment]
not relevant
