### ISSUE TITLE
(SP: 0.5) Check PasswordSecurityTab.tsx warning

### ISSUE THREAD

**Issue by abalanovsky** [ita-social-projects/SpaceToStudy-Client#1973]
Check PasswordSecurityTab.tsx warning

<img width="1168" alt="Знімок екрана 2024-06-19 о 14 16 22" src="https://github.com/ita-social-projects/SpaceToStudy-Client/assets/108689551/f44705d6-7638-4696-ba64-154e99548ab2">

**Comment by PavloDolia** [comment]
task is not relevant. Couldn't reproduce this bug
<img width="415" alt="Screenshot 2024-07-23 at 15 16 36" src="https://github.com/user-attachments/assets/7df80f75-6c53-4ebd-a475-e6d97ff2e692">
