### ISSUE TITLE
(SP: ) do not refresh the profile edit page after saving data 

### ISSUE THREAD

**Issue by Mygal-Alex** [ita-social-projects/SpaceToStudy-Client#1978]
![image](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/101183408/1a33df12-e245-435e-8408-2f1085a1c588)
after pressing the abate button 
do not refresh the profile edit page after saving data

**Comment by YaroslavChuiko** [comment]
This issue is not relevant, as it was decided to rework the logic of this component using Redux
