### ISSUE TITLE
Epic: Rewrite profile edit

### ISSUE THREAD

**Issue by abalanovsky** [ita-social-projects/SpaceToStudy-Client#2016]
Rewrite profile edit

All switching between tabs should happen **without Confirm**. 
The data should be updated after clicking on one common "Save" button and should be displayed without reloading. 
The Password & Security tab should have its own Confirm to confirm a password change.
It is also necessary to display Confirm if the changes have not been saved and the user wants to leave the editing page

№ | Issue | Link | Status |
-- | -- | --  | -- |
1 | Setup Profile Redux slice | #2017 |
2 | Rewrite profile edit | #2018 |
3 | Rewrite Professional info | #2019 |
4 | Rewrite Notifications tab | #2020 |
5 | Add password save Confirmation | #2021 |
6 | Implement Save button | #2022 |
7 | Check profile edit Confirms | #2023  |

**Comment by YaroslavChuiko** [comment]
This epic was accomplished
