### ISSUE TITLE
(SP: 2) Implement Update button

### ISSUE THREAD

**Issue by abalanovsky** [ita-social-projects/SpaceToStudy-Client#2022]
Remove ``Back to your personal profile`` button, and implement ``Update`` button instead. Button should be disabled until the data changes.
Send and change data after save.

Epic #2016 blocked by #2020
Figma [link](https://www.figma.com/design/liJZDYhUnDP15Pi9bipDcv/Space2Study-(Students)?node-id=19153-61719&t=zZaXT9OIGQpPRugX-4) 

<img width="635" alt="Знімок екрана 2024-07-01 о 11 26 50" src="https://github.com/ita-social-projects/SpaceToStudy-Client/assets/108689551/557cd16f-077e-485a-a401-ce9a41f38202">
<img width="568" alt="Знімок екрана 2024-07-01 о 11 27 02" src="https://github.com/ita-social-projects/SpaceToStudy-Client/assets/108689551/9e3e320f-8b03-4ace-a453-14cade9078ef">

**Comment by docia** [comment]
and its good to check out this Task #1952 all along with the current task
