### ISSUE TITLE
(SP: 2) Check profile edit Confirms

### ISSUE THREAD

**Issue by abalanovsky** [ita-social-projects/SpaceToStudy-Client#2023]
Confirmations should be absent when switching between the Profile, professional info & notifications tabs.
If the user exits the editing page, a confirmation should appear

<img width="615" alt="Знімок екрана 2024-07-01 о 11 31 04" src="https://github.com/ita-social-projects/SpaceToStudy-Client/assets/108689551/ffa6bade-9eac-407d-bbce-ebeccf727243">

Epic #2016

**Comment by docia** [comment]
not relevant anymore
