### ISSUE TITLE
(SP: ) Increase CreateOrEditLesson.tsx coverage

### ISSUE THREAD

**Issue by abalanovsky** [ita-social-projects/SpaceToStudy-Client#2036]
Increase CreateOrEditLesson.tsx coverage

<img width="695" alt="Знімок екрана 2024-07-02 о 13 22 12" src="https://github.com/ita-social-projects/SpaceToStudy-Client/assets/108689551/1bf657fb-14e4-479a-b1b9-f9794de97182">

**Comment by docia** [comment]
closed as duplicate #2134
