### ISSUE TITLE
Fix sending refreshToken with every API request

### ISSUE THREAD

**Issue by Olenka-Hryk** [ita-social-projects/SpaceToStudy-Client#2066]
### Unnecessary sending of `refreshToken` on every API call
Currently, both the `refreshToken` and `accessToken` are being sent **with every API request**, which is unnecessary and potentially insecure. This can expose the `refreshToken` to unauthorized access and increase the risk of token theft.

**Steps to reproduce:**
1. Make an API call to any endpoint
2. Inspect the request headers or body
3. Observe that both `refreshToken` and `accessToken` are being sent
<img width="1370" alt="Screenshot 2024-07-08 at 17 45 27" src="https://github.com/ita-social-projects/SpaceToStudy-Client/assets/28622400/425ab455-ca7b-4a27-b909-efae2065021a">

<img width="1150" alt="Screenshot 2024-07-08 at 17 48 48" src="https://github.com/ita-social-projects/SpaceToStudy-Client/assets/28622400/f462eac3-60d7-4259-904c-3fa7015141b2">

**Expected behavior:** Only the `accessToken` should be sent with API requests, and the `refreshToken` should be stored securely on the client-side and only used to request a new `accessToken` when the current one is close to expiring or has already expired.

**Comment by PavloDolia** [comment]
The `refreshToken` is stored in httpOnly cookies, therefore the token is sent with every API request by a browser and we can't control this with javascript
