### ISSUE TITLE
(SP: 1) Fix availability icon display after saving cooperation to match Figma design

### ISSUE THREAD

**Issue by Olenka-Hryk** [ita-social-projects/SpaceToStudy-Client#2102]
on hold: waiting for new design
### Align Availability Icon with Figma Design
After updating the **availability status of a cooperation resource** (e.g., changing the `date` format or setting it to `closed`) and saving, the displayed status does not match the selected availability. Currently, only an icon `Open` is shown near open resources:
<img width="1213" alt="Screenshot 2024-07-15 at 17 38 27" src="https://github.com/user-attachments/assets/25a1a213-1011-493e-b50c-959770b53528">
### Expected Result:
The availability status of all cooperation resources should be displayed correctly, consistent with the [Figma design](https://www.figma.com/design/liJZDYhUnDP15Pi9bipDcv/Space2Study-(Students)?node-id=13595-60485&t=Vk1H26X2MtFc4B1x-4), and properly reflect the status of `Open`, `Open from date`, and `Closed` resources:
<img width="1173" alt="Screenshot 2024-07-15 at 17 11 02" src="https://github.com/user-attachments/assets/d06ee03e-32e9-4427-a560-4a9a3dcd28db">

**Comment by ipasic-softserve** [comment]
Not relevant
