### ISSUE TITLE
(SP: 1) Update redux and redux toolkit

### ISSUE THREAD

**Issue by YaroslavLys** [ita-social-projects/SpaceToStudy-Client#2123]
Investigate `@reduxjs/toolkit` and `react-redux` update

![image](https://github.com/user-attachments/assets/e3d6bc11-eb55-4a11-9e30-a4f7c50eb1b9)
![image](https://github.com/user-attachments/assets/ab41d355-8b82-45a5-83f7-8e3eb6506c6d)

**Comment by YaroslavChuiko** [comment]
Successfully merged
