### ISSUE TITLE
(SP: 2) Change working hours ProfileItem

### ISSUE THREAD

**Issue by abalanovsky** [ita-social-projects/SpaceToStudy-Client#2137]
Change ``Set up your working hours`` to ``Education`` add description on your own

<img width="902" alt="Screenshot 2024-07-23 at 12 20 26" src="https://github.com/user-attachments/assets/cc335e06-e331-4e6e-8ced-37153a1231a8">

## Design needed @Nastia197

**Comment by YaroslavChuiko** [comment]
This issue is not relevant
