### ISSUE TITLE
(SP: 1) Rewrite LoginForm to tsx format and fix the sonar issues

### ISSUE THREAD

**Issue by Mygal-Alex** [ita-social-projects/SpaceToStudy-Client#2192]
![image](https://github.com/user-attachments/assets/239e6eb6-8f92-4645-b630-464f50a3dd44)
![image](https://github.com/user-attachments/assets/e67064ab-0d4b-4576-b572-7283fd8eec07)

**Comment by Pasichnichenkoilya** [comment]
Duplicate #2184
