### ISSUE TITLE
(SP: 1) Rewrite report-web-vitals

### ISSUE THREAD

**Issue by Mygal-Alex** [ita-social-projects/SpaceToStudy-Client#2206]
![image](https://github.com/user-attachments/assets/2b2bc8fe-2926-496e-9ba7-3cf88a4d90f2)
![image](https://github.com/user-attachments/assets/bbef31b0-67f5-4793-9823-17c1a58f811c)

**Comment by YaroslavChuiko** [comment]
It might be related to #2143
