### ISSUE TITLE
( SP: ) check videolink types and ensure it is saved on backend after we click the Update button on the EditProfile page

### ISSUE THREAD

**Issue by docia** [ita-social-projects/SpaceToStudy-Client#2262]
- [ ] check videolink types 
- [ ]  ensure the videolink is saved on backend after we click the Update button on the EditProfile page

**Comment by YulichkaR** [comment]
fixed by #2259 

![image](https://github.com/user-attachments/assets/d34941d9-ac80-4912-9833-133ee847f7c5)
![image](https://github.com/user-attachments/assets/1ce03ed7-3643-423a-a825-f4cf3dfba333)
![image](https://github.com/user-attachments/assets/6278ebd5-7f7c-4d56-9b0a-38bc0f6c2fc9)
