### ISSUE TITLE
(SP: ) create alert for successful update user data on the EditProfile

### ISSUE THREAD

**Issue by docia** [ita-social-projects/SpaceToStudy-Client#2348]
- [x] after clicking the Update button, the alert should appear

<img width="815" alt="Screenshot 2024-08-15 at 14 24 21" src="https://github.com/user-attachments/assets/b1ad199a-91c3-4fdc-88b3-c1c6dc52c3f0">

Example:
![editprofile](https://github.com/user-attachments/assets/23faab58-5f76-4ade-9d9e-bf52ffafd0f8)

**Comment by YulichkaR** [comment]
closed, because it merged into [enhancement/2022/update-btn-on-profiletab] branch
