### ISSUE TITLE
(SP: ) Change header

### ISSUE THREAD

**Issue by abalanovsky** [ita-social-projects/SpaceToStudy-Client#2367]
Change header according to new design

[Figma link
](https://www.figma.com/design/liJZDYhUnDP15Pi9bipDcv/Space2Study-(Students)?node-id=19977-46223&t=1Sn2p1B4STyEBmKE-4)
<img width="951" alt="Знімок екрана 2024-08-21 о 15 38 16" src="https://github.com/user-attachments/assets/0e6c0cff-345f-4615-a24f-bd25e5a6c1d0">

**Comment by YaroslavChuiko** [comment]
Closed by #2380
