### ISSUE TITLE
 (SP: 1) Fix size of the offer card (list/grid view) on bookmarks page

### ISSUE THREAD

**Issue by ipasic-softserve** [ita-social-projects/SpaceToStudy-Client#2422]
![image](https://github.com/user-attachments/assets/44c790d1-ef56-4cc1-9e9a-6b4a6d424c61)
![image](https://github.com/user-attachments/assets/6d71f68d-5503-4234-81e5-e08ec276c9ad)

For reference use [Figma](https://www.figma.com/design/liJZDYhUnDP15Pi9bipDcv/Space2Study-(Students)?node-id=20789-78245&t=xqVXv7X3GxzUT90m-4)

**Comment by nebby2105** [comment]
This issue is a duplicate and has already been resolved
