### ISSUE TITLE
(SP: 0.5) Fix text on the filter drawer on My Courses page

### ISSUE THREAD

**Issue by YaroslavLys** [ita-social-projects/SpaceToStudy-Client#2430]
**Description:** Fix text on the filter drawer on My Courses page. [UA translation]

**Expected:** Обрати рівні.

**Actual:** Обратирівні.

![Screenshot 2024-09-03 at 12 41 45](https://github.com/user-attachments/assets/fd84779d-ffff-4b67-b8fa-ac66906471c1)

**Comment by BohdanMylyi** [comment]
already done
