### ISSUE TITLE
(SP: 0.5) User should not have the opportunity to sent files

### ISSUE THREAD

**Issue by YaroslavLys** [ita-social-projects/SpaceToStudy-Client#2489]
**Description:** A user should not have the opportunity to send files in the big chat.

![Screenshot 2024-09-10 at 15 46 44](https://github.com/user-attachments/assets/6fcee88b-4267-4b06-9d22-e34b75c27523)

**Comment by YaroslavChuiko** [comment]
Closed by  #2501
