### ISSUE TITLE
(SP: 2) Check useChangeConfirm hook on certain requirements

### ISSUE THREAD

**Issue by Olenka-Hryk** [ita-social-projects/SpaceToStudy-Client#2506]
### Check useChangeConfirm hook on certain requirements
Check if the next requirements are implemented in [PR #2410](https://github.com/ita-social-projects/SpaceToStudy-Client/pull/2410/files). If not, then implement it:

- [ ] Confirm message should display all `courses` AND `cooperations` that have the current resource that the user wants to edit or delete. It seems that it checks only `courses` but not includes `cooperations`:
<img width="404" alt="Screenshot 2024-09-12 at 00 25 32" src="https://github.com/user-attachments/assets/1366c83d-ce3e-47ca-9627-4cdcbc8bcd32">

- [ ] Confirm message should display all **ACTIVE** `cooperations` that have the current resource that the user wants to edit or delete. 

### IMPORTANT:
**Also, you need to ask our tech lead and designer for a mockup - because in the requirements, if a _resource_ is added to an `active` AND `closed` cooperation or a _course_ is added to an `active` and `closed` cooperation, and the tutor wants to make this change or delete, then the tutor must send a request to all students to ask for permission on changing or deleting the current resource/course.**

**Comment by PavloDolia** [comment]
the hook deleted in PR [#2553](https://github.com/ita-social-projects/SpaceToStudy-Client/pull/2553)

**Comment by PavloDolia** [comment]
the hook deleted in PR [#2553](https://github.com/ita-social-projects/SpaceToStudy-Client/pull/2553)
