### ISSUE TITLE
Epic: Create a possibility to add a Course as a copy or link to a Cooperation

### ISSUE THREAD

**Issue by Olenka-Hryk** [ita-social-projects/SpaceToStudy-Client#2507]
### [ Epic ] Create a possibility to add a `Course` as a `copy` or `link` to a `Cooperation`

Add a possibility to add a course to a cooperation by two ways: by `linking` and as a `duplicated copy`. Currently, the system only supports adding courses as a duplicate copy.
Link: https://excalidraw.com/#json=aErJ68u6pn5EHYV7vbLVh,wrp8pBjiHa23ImjpGYXgkA

**It is a complex task that needs to be divided into smaller tasks on both frontend and backend sides.**

<img width="1144" alt="possibility to add course as link or copy" src="https://github.com/user-attachments/assets/2b6397a8-14cf-4c32-b3f3-ac691ad4910a">

**Comment by YaroslavChuiko** [comment]
This epic was successfully accomplished
