### ISSUE TITLE
(SP: ) Fix the search bar for chat messages

### ISSUE THREAD

**Issue by PavloDolia** [ita-social-projects/SpaceToStudy-Client#2523]
If there are no results matching the request, the counter of matches is in the form of “0 of 0” with the inactive down-stepper icon button from the left and the inactive up-stepper icon button from the right and nothing happens.

https://github.com/user-attachments/assets/faa91a95-a25c-4d66-9603-848cbc25ede0

**Comment by Mav-Ivan** [comment]
not relevant
