### ISSUE TITLE
(SP: ) Error in console_find offers

### ISSUE THREAD

**Issue by OliaHrytsak** [ita-social-projects/SpaceToStudy-Client#2536]
This error occurs when click on 'all offers'

![image](https://github.com/user-attachments/assets/54c62ded-5ee9-4a17-9944-ecbe3d8a7739)

![image](https://github.com/user-attachments/assets/99e1d558-16f8-4bf2-af9b-91cc8574b2a5)

**Comment by YaroslavChuiko** [comment]
This task isn't relevant anymore. I can't reproduce the bug
