### ISSUE TITLE
[Edit profile. Professional info] Verify that when the user enters invalid values in the "About the tutor"/"About the student" sections, the maximum valid number of characters is saved.

### ISSUE THREAD

**Issue by MilaKomisarenko** [ita-social-projects/SpaceToStudy-Client#2828]
Test case verifies the flow for a Tutor and a Student simultaneously that when the user enters invalid values in the "About the tutor"/"About the student" sections, the maximum valid number of characters is saved.

**Preconditions:**
1. The user is logged in https://s2s-front-stage.azurewebsites.net/tutor as a Tutor/Student.
2. “My profile” => “Edit profile” => “Professional info” page is opened.

Test Steps:
1. Go to the “About the tutor” section ( the “About the student” section).
_Expected result:_
The “About the tutor” section ( the “About the student” section) is displayed under the “Edit category” section.

2. Click on the “Education” accordion.
_Expected result:_
The text field is opened.

3. Type invalid value:
_Test Data:_
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam.X
_Expected result:_
The word countdown is highlighted in red. Only 1000 symbols are displayed. The button “Update” is enabled.

4. Click the button "Update".
_Expected result:_
Only the first 1000 symbols are saved. 

5. Go to the "My profile" page.
_Expected result:_
The text is displayed on the "My profile" page.

6. Repeat the steps for “Work experience”, “Scientific activities”, “Awards” accordions.

User story link [Edit Tutor's profile. Professional info. # 2694] (https://github.com/ita-social-projects/SpaceToStudy-Client/issues/2694)
[Edit Student's profile. Professional info. # 2695] (https://github.com/ita-social-projects/SpaceToStudy-Client/issues/2695)

**Comment by dudchakk** [comment]
closed as done
