### ISSUE TITLE
(SP: 0.5) Sort the arguments in long RUN instructions

### ISSUE THREAD

**Issue by Made1ra** [ita-social-projects/SpaceToStudy-Client#2852]
In Dockerfiles, when commands within a RUN instruction have a lot of arguments, especially those that install system packages, it is important to ensure that the arguments are sorted alphabetically. This practice enhances the readability and maintainability of the code. It allows for easier tracking of modifications and can help prevent potential errors.

You can see a detailed description of the issue by the [link](https://github.com/ita-social-projects/SpaceToStudy-Client/security/code-scanning/2).

<img width="1250" alt="Screenshot 2024-11-23 at 11 19 01" src="https://github.com/user-attachments/assets/e7a77ef3-1e80-440b-be61-370c7793efa6">

**Comment by qwqw-333** [comment]
We will rewrite dockerfile soon, because using ssh in container - isn't a good solution.

**Comment by Made1ra** [comment]
Okay, then I will close the issue.
