### ISSUE TITLE
Fix name overflow in "Cooperation Offer" card in "Accept new cooperation" modal window

### ISSUE THREAD

**Issue by luiqor** [ita-social-projects/SpaceToStudy-Client#2871]
Users are allowed a maximum of 30 characters for both first and last names.

Users with long first and last names experience price and status spilling outside of the "Cooperation Offer" card.

![image](https://github.com/user-attachments/assets/ab0c7f2d-df3d-4282-b6c0-8c8e0201a0e1)

**Comment by Made1ra** [comment]
Cannot reproduce it in production, I think you can close the issue.
