### ISSUE TITLE
(SP: _) [Tutor's Homepage] Implement progress bar

### ISSUE THREAD

**Issue by KhrystynaPavlikovska** [ita-social-projects/SpaceToStudy-Client#449]
Reuse progress bar container for tutor's 'Home page' (from tutor's 'Profile').

[FIGMA](https://www.figma.com/file/liJZDYhUnDP15Pi9bipDcv/Space2Study-(Students)?node-id=2140%3A54676&t=bk9rcFzS3qH97FfM-1)

![image](https://user-images.githubusercontent.com/34419998/219356758-3ef37501-92b5-4c10-b834-af80cf43ef2b.png)

**Comment by ipasic-softserve** [comment]
Duplicate #408
