### ISSUE TITLE
(SP: _) [Tutor's Homepage]  Implement search bar

### ISSUE THREAD

**Issue by KhrystynaPavlikovska** [ita-social-projects/SpaceToStudy-Client#450]
Reuse search bar container for tutor's 'Home page' (from student's 'Home page').

![image](https://user-images.githubusercontent.com/34419998/219357050-0bdcf970-8e07-4b25-907e-f9132e260ded.png)

**Comment by ipasic-softserve** [comment]
Duplicate #859
