### ISSUE TITLE
(SP: 1)[Find Offer Page] Implement block "Tutors for private lessons"

### ISSUE THREAD

**Issue by radomyr-horban** [ita-social-projects/SpaceToStudy-Client#467]
Implement block "Tutors for private lessons" on 'Find Offer Page'.

! (Design can be different from the photo. You should check it before work).
[FIGMA](https://www.figma.com/file/liJZDYhUnDP15Pi9bipDcv/Space2Study-(Students)?node-id=3426%3A63844&t=9vKh3UgKHpnS4W8t-0)

![student-find-private-lessons](https://user-images.githubusercontent.com/68649827/219659496-5027afb6-022e-43bb-bcc8-d6922828a54e.png)

**Comment by YulichkaR** [comment]
not relevant
