### ISSUE TITLE
[Forgot password page]The page is closed when clicking outside the popup

### ISSUE THREAD

**Issue by IrynaCHR** [ita-social-projects/SpaceToStudy-Client#640]
**Description:** 
When a User clicks outside the 'Forgot password' popup  – nothing happens.

**Environment**: Google Chrom 112.0.5615.137 (Official), (x86_64)
**Reproducible:** always.

**Precondition:**
The 'Forgot password' popup is opened.

**Steps to reproduce:**
1. Click outside the "Forgot password" popup.

**Actual result:**
The "Forgot password" popup is closed and the user is redirected to the guest start page.

**Expected result:**
The "Forgot password" popup is opened.

**Comment by DLmar** [comment]
It was fixed in different issue: https://github.com/ita-social-projects/SpaceToStudy-Client/pull/785
