### ISSUE TITLE
[Forgot password page]The user is redirected to the Guest home page after clicking the 'x' button

### ISSUE THREAD

**Issue by IrynaCHR** [ita-social-projects/SpaceToStudy-Client#641]
**Description:** When a User clicks the 'x' (Close) button – the popup closes and the User goes to the Login popup.

**Environment:** Google Chrom 112.0.5615.137 (Official), (x86_64)

**Reproducible:** always.

**Precondition:**
The 'Forgot password' popup is opened.

**Steps to reproduce:**
Click the 'x' button in the right upper corner.

**Actual result:**
The user is redirected to the Guest home page when the User clicks the 'x' button 

**Expected result:**
When a User clicks the 'x' button – the popup closes and the User goes to the Login popup.

**Comment by DLmar** [comment]
We decided to close the issue, because there's already a button on popup that will redirect user to Login popup, so there's no need in to do this with 'x' button
