### ISSUE TITLE
(SP: 0.5) Fix typeError in OfferCardSquare.tsx component

### ISSUE THREAD

**Issue by ArturBekhDEV** [ita-social-projects/SpaceToStudy-Client#653]
Fix this TS bug:

![image](https://github.com/user-attachments/assets/40038e07-509d-421e-b3a1-862962370515)

**Comment by docia** [comment]
as I see, the test coverage for OfferCardSquare is 100%
Is this task still relevant?
<img width="1470" alt="Screenshot 2024-06-18 at 14 17 07" src="https://github.com/ita-social-projects/SpaceToStudy-Client/assets/102433497/ff6909fe-9e20-4161-9771-3bd71a9f3a03">


@ArturBekhDEV could you clarify the bug which should be fixed? and if it is still relevant as well.
