### ISSUE TITLE
[Mentor 'Sign Up' pop-up] the text "Already have a Space2Study account? Log In" doesn't correspond the requirements

### ISSUE THREAD

**Issue by ValeriiaSnitkoQA** [ita-social-projects/SpaceToStudy-Client#686]
**Defect Type:** UI/Usability
**Severity:** Trivial
**Priority:** Low
**Reproducible:** Always
**Environment:** Windows 10 21H2, Chrome 110.0.5481.178

**Description:** 
The text "Already have a Space2Study account? Log In" doesn't correspond the requirements

**Preconditions:**
The web-page https://s2s-front-stage.azurewebsites.net/ is opened, the button "Become a Tutor" is clicked and the "Tutor Sign Up" pop-up appeared.

**Steps to reproduce:**
Take a look at the text below the "Sign Up with Google" button.

**Actual result:**
The text under "Sign Up with Google" button is "Already have a tutor account? Login!" and it is not corresponding the mockup.
![image](https://user-images.githubusercontent.com/129952218/236566580-618da68c-afd7-4466-a259-2504508ce737.png)

**Expected result:**
The text under "Sign Up with Google" button is "Already have a Space2Study account? Log In!" and is matching to mockup.

**Comment by rakib13x** [comment]
have you fixed the bug?if not,then I am Interested to fixed this.
