### ISSUE TITLE
[SP:1] Reconstruct the grid for whole project.

### ISSUE THREAD

**Issue by FryDay969** [ita-social-projects/SpaceToStudy-Client#698]
The goal is to change the width for all models, grid and complex blocks on the projects.

**Comment by docia** [comment]
@FryDay969 can you specify what specific width you offer to change for?
can you provide any visual example of how you expect those models, grids and complex blocks to be displayed?

**Comment by YaroslavChuiko** [comment]
This epic isn't relevant anymore
