### ISSUE TITLE
Fix jumping input

### ISSUE THREAD

**Issue by DLmar** [ita-social-projects/SpaceToStudy-Client#930]
Fix jumping input in InputWithIcon component

Bug reveals in mobile screen resolution
![firefox_s1zD0maCZd](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/45912519/d78cab3e-4ac3-4245-8ea4-eb8b0ac59853)

**Comment by TSlashDreamy** [comment]
Bug reveals in mobile screen resolution
![firefox_s1zD0maCZd](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/45912519/d78cab3e-4ac3-4245-8ea4-eb8b0ac59853)
