### ISSUE TITLE
Fix breadcrumb last element position

### ISSUE THREAD

**Issue by TSlashDreamy** [ita-social-projects/SpaceToStudy-Client#935]
Typography in breadcrumbs is not aligned.

![зображення](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/45912519/7d9cbb55-7310-4163-a221-7869b223d993)
![зображення](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/45912519/e044b51d-f367-49cd-b26c-2d655c6cbdec)

**Comment by anmol111pal** [comment]
hey @TSlashDreamy , i am willing to work on this issue/bug.
Plz assign this to me
